steps:
- script: | 
    echo hello beautiful world! %MyName%
    echo verifying a change with touch
    echo Agent.HomeDirectory is %CD%
    ver
  env:
    MyName: $(Agent.MachineName)

- task: Docker@0
  inputs:
    containerregistrytype: 'Container Registry'
    imageName: 'lavielp/uw-it-helloworld:$(Build.BuildId)'
    qualifyImageName: false
    includeLatestTag: true

- task: Docker@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub lavielp'
    action: 'Push an image'
    imageName: 'lavielp/uw-it-helloworld:$(Build.BuildId)'
    qualifyImageName: false
    includeLatestTag: true

- task: Kubernetes@0
  inputs:
    kubernetesServiceConnection: 'ACS Kubernetes'
    useConfigurationFile: true
    configuration: k8.helloworld.yml

- task: Kubernetes@0
  inputs:
    kubernetesServiceConnection: 'ACS Kubernetes'
    command: set
    arguments: 'image deployment/helloworld helloworld=lavielp/uw-it-helloworld:$(Build.BuildId) --record'
