steps:
- script: | 
    echo hello beautiful world! %MyName%
    echo verifying a change
    echo Agent.HomeDirectory is %CD%
    ver
  env:
    MyName: $(Agent.MachineName)

- task: Docker@0
  inputs:
    containerregistrytype: 'Container Registry'
    imageName: 'lavielp/uw-it-helloworld'
    qualifyImageName: false
    includeLatestTag: true

- task: Docker@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Docker Hub lavielp'
    action: 'Push an image'
    imageName: 'lavielp/uw-it-helloworld'
    qualifyImageName: false
    includeLatestTag: true

- task: Kubernetes@0
  inputs:
    kubernetesServiceConnection: 'ACS Kubernetes Down Level'
    useConfigurationFile: true
    configuration: k8.helloworld.yml
