apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    run: helloworld
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: howtoapp
    # run: helloworld
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: helloworld
#   labels:
#     app: howtoapp
# spec:
#   containers:
#   - name: helloworld
#     image: lavielp/uw-it-helloworld:latest
#     imagePullPolicy: Always
#     ports: 
#     - containerPort: 80
#   imagePullSecrets:
#   - name: acr-auth
#   nodeSelector:
#     beta.kubernetes.io/os: windows
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: howtoapp
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: howtoapp
  template:
    metadata:
      labels:
        name: helloworld
        app: howtoapp
    spec:
      containers:
      - name: helloworld
        image: lavielp/uw-it-helloworld:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
      imagePullSecrets:
      - name: dh-auth
      nodeSelector:
        beta.kubernetes.io/os: windows