apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    run: helloworld
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: howtoapp
    # run: helloworld
---
apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    app: howtoapp
spec:
  containers:
  - name: helloworld
    image: winengtestcontainerregistry.azurecr.io/howto:latest
    imagePullPolicy: Always
    ports: 
    - containerPort: 80
  imagePullSecrets:
  - name: acr-auth
  nodeSelector:
    beta.kubernetes.io/os: windows
---
# apiVersion: v1
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: helloworld
#   labels:
#     app: howtoapp
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: helloworld
#       name: helloworld
#     spec:
#       containers:
#       - name: helloworld
#         image: winengtestcontainerregistry.azurecr.io/howto:33
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 80
#       imagePullSecrets:
#       - name: acr-auth
#       nodeSelector:
#         beta.kubernetes.io/os: windows